import math, logging

from copy import deepcopy
from typing import TYPE_CHECKING

from spycci.constants import atoms_dict

from rdkit.Chem import rdchem, rdmolops, rdDetermineBonds

if TYPE_CHECKING:
    from spycci.systems import System

logger = logging.getLogger(__name__)


def get_total_charge(mol: rdchem.Mol) -> int:
    """
    Given a `rdkit.Chem.rdchem.Mol` object the function computes the total charge of the molecule as the sum 
    of formal charges on the atoms.

    Arguents
    --------
    mol: rdchem.Mol
        The `rdkit.Chem.rdchem.Mol` object encoding the molecular structure.

    Raises
    ------
    TypeError
        Exception raised if the argument is not of type `rdkit.Chem.rdchem.Mol` or `rdkit.Chem.rdchem.RWMol`.
    
    Returns
    -------
    int
        The total charge of the molecule as the sum of formal charges.
    """
    if isinstance(mol, (rdchem.Mol, rdchem.RWMol)) is False:
        raise TypeError("The `mol` argument must be of type `rdkit.Chem.rdchem.Mol` or `rdkit.Chem.rdchem.RWMol`")
    return sum([atom.GetFormalCharge() for atom in mol.GetAtoms()])


def get_number_of_radicals(mol: rdchem.Mol) -> int:
    """
    Given a `rdkit.Chem.rdchem.Mol` object the function computes the total number of radical electrons in the molecule.

    Arguents
    --------
    mol: rdchem.Mol
        The `rdkit.Chem.rdchem.Mol` object encoding the molecular structure.

    Raises
    ------
    TypeError
        Exception raised if the argument is not of type `rdkit.Chem.rdchem.Mol` or `rdkit.Chem.rdchem.RWMol`.
    
    Returns
    -------
    int
        The total number of radical electrons.
    """
    if isinstance(mol, (rdchem.Mol, rdchem.RWMol)) is False:
        raise TypeError("The `mol` argument must be of type `rdkit.Chem.rdchem.Mol` or `rdkit.Chem.rdchem.RWMol`")
    return sum([atom.GetNumRadicalElectrons() for atom in mol.GetAtoms()])


def system_to_mol(system: "System", catch_errors: bool = True) -> rdchem.Mol:
    """
    Given a `System` object, the function generates an `rdkit.Chem.Mol` object from the stored molecular
    geometry, system charge, and spin. The function is based on RDKit and creates a `Mol` object by directly
    converting the stored system geometry in memory through an intermediate `RWMol` read-write molecule object.
    The connectivity of the molecule is automatically assigned using a workflow based on the `DetermineBonds`
    function from the `rdkit.Chem.rdDetermineBonds` module. The conversion process is higly heuristical and
    has been designed to patch some of the limitations of the `DetermineBonds` function in the case of open-shell
    systems. In these cases, bond determination may temporarily adjust the total charge of the system by adding
    or removing electrons (charge-shifting) to create a hypothetical singlet (closed-shell) configuration. The
    obtained connectivity is then copied back to the original molecule, and, for radical systems, radical electrons
    and formal charges are assigned and sanitized using the `SANITIZE_PROPERTIES` and `SANITIZE_FINDRADICALS` 
    options. Implicit hydrogens are not added by default, so radical sites and hydrogen counts are explicit.
    If Mulliken spin populations are available within the system properties, these are automatically used to help
    in the connectivity determination. When spin populations are available, radical sites are set at the beginning
    of the connectivity assignent procedure and are enforced, by adjusting bond orders, when copying the 
    singlet connectivity generated by the charge-shifting approach.

    BEWARE that this function is highly experimental and can fail with open-shell systems or non-standard
    valences. The user MUST carefully review the function output.

    Arguments
    ---------
    catch_errors: bool
        If set to `True` (default), will not rise an exception if sanitization fails due to non-standard
        valences. If `False` exception is raised.

    Returns
    -------
    rdkit.Chem.Mol
        An RDKit `Mol` object representing the molecule with explicit hydrogens, 
        connectivity, formal charges, and radical electrons (if any).
    """

    logger.info(f"Generating RDKit Mol object from '{system.name}' system (charge: {system.charge}, spin: {system.spin})")

    # Create an empty instance of a read-write molecule object
    rwmol = rdchem.RWMol()

    # Initialize the atom list of the `Mol` object with the system `atoms` list 
    atomic_numbers = {a: i for i, a in atoms_dict.items()}
    for atom in system.geometry.atoms:
        rd_atom = rdchem.Atom(atomic_numbers[atom])
        rd_atom.SetNoImplicit(True)
        rwmol.AddAtom(rd_atom)

    # If Mulliken spin populations are available, use them to set the position of radicals
    radicals = [0 for _ in range(system.geometry.atomcount)]
    spin_populations = system.properties.mulliken_spin_populations
    if spin_populations != [] and system.spin>1:
        logger.debug("- Mulliken spin populations available: Using spin populations to help in radical site determination.")

        ordered = [(i, s) for i, s in enumerate(spin_populations)]
        ordered.sort(key=lambda x: x[1], reverse=True)
        
        for i, s in ordered:
            radicals[i] = math.ceil(s)

            if sum(radicals) + 1 > system.spin:
                radicals[i] -= sum(radicals) + 1 - system.spin
            
            if sum(radicals) + 1 == system.spin:
                break
        
        logger.debug(f"    -> Radicals assignment: {radicals}")

        for i, s in enumerate(radicals):
            if s>0:
                atom = rwmol.GetAtomWithIdx(i)
                atom.SetNumRadicalElectrons(s)

    # Convert the read-write molecule object to a standard `Mol` object
    mol = rwmol.GetMol()

    # Assign a conformer to the `Mol` object holding the coordinates of the atoms in the system
    conf = rdchem.Conformer(system.geometry.atomcount)
    for i, coords in enumerate(system.geometry.coordinates):
        conf.SetAtomPosition(i, coords)

    mol.AddConformer(conf, assignId=True)

    # Connectivity assignment using the `DetermineBonds` function
    # --------------------------------------------------------------------------------------------------------
    # If system is singlet, try connectivity assignment as is or convert to triplet
    # If system is multiplet, try connectivity assignment using charge shift
    
    if system.spin == 1:

        try:
            logger.debug("- System is in singlet state: running connectivity determination as is.")
            rdDetermineBonds.DetermineBonds(mol, charge=system.charge, embedChiral=True, allowChargedFragments=True)
        
        except:
            logger.debug("    -> Connectivity assignment FAILED")
            
            # Note: Triplet conversion is largely unused due to conversion to charge pair 
            logger.warning("ASSUMING molecule is a di-radical in singlet state: running conversion using TRIPLET state.")
            obj = deepcopy(system)
            obj.spin = 3
            mol = obj.__generate_mol(catch_errors)

        else:
            logger.debug("    -> Connectivity assignment SUCCESS")            
    
    else:
        logger.debug("- System is open-shell: running heuristic connectivity determination by charge shift.")

        # Variable type definition to help typing
        newmol: rdchem.Mol = None
        bond: rdchem.Bond = None
    
        for charge_shift in [0, system.spin - 1, -(system.spin - 1)]:
            
            try:
                newmol = deepcopy(mol)
                newcharge = system.charge + charge_shift
                logger.debug(f"- Trying : connectivity assignmet with charge: {newcharge}")
                rdDetermineBonds.DetermineBonds(newmol, charge=newcharge, embedChiral=True, allowChargedFragments=True)
            
            except:
                logger.debug("    -> Connectivity assignment FAILED")
                continue

            else:
                logger.debug("    -> Connectivity assignment SUCCESS")
                break
        
        else:
            msg = f"Connectivity assignment failed for open-shell system `{system.name}`"
            logger.error(msg)
            raise RuntimeError(msg)
        
        # Copy the obtained connectivity to a temporary read-write `Mol` object  
        tmp_rwmol = rdchem.RWMol(mol)

        radical_on_aromatic = False
        for bond in newmol.GetBonds():
            i = bond.GetBeginAtomIdx()
            j = bond.GetEndAtomIdx()
            tmp_rwmol.AddBond(i, j, bond.GetBondType())

            # Check if one of the radicals set using spin populations is set on an aromatic system
            if bond.GetIsAromatic() is True:
                if radicals[i] > 0 or radicals[j] > 0:
                    radical_on_aromatic = True
        
        # If no radical was set (with spin populations), directly convert to `Mol` object
        if sum(radicals) == 0:
            logger.debug("- Success: Radical assignment not found, using RDKit to find radicals.")
            
            mol = tmp_rwmol.GetMol()

            # Sanitize the molecule setting charges and radicals
            rdmolops.SanitizeMol(
                mol,
                sanitizeOps=rdmolops.SanitizeFlags.SANITIZE_PROPERTIES | rdmolops.SanitizeFlags.SANITIZE_FINDRADICALS,
                catchErrors=catch_errors
            )

        # If radicals were set (with spin populations) check if they are compatible with singlet connectivity
        else:
            logger.debug("- Radical assignment FOUND:")
            logger.debug("    -> Checking if system is compatible with direct copy and PROPERTIES sanitization.")

            sanitized_mol = tmp_rwmol.GetMol()
            
            rdmolops.SanitizeMol(
                sanitized_mol,
                sanitizeOps=rdmolops.SanitizeFlags.SANITIZE_PROPERTIES,
                catchErrors=catch_errors
            )

            charge = get_total_charge(sanitized_mol)
            nrad = get_number_of_radicals(sanitized_mol)

            if charge == system.charge and nrad + 1 == system.spin:
                logger.debug("- Success: Directly adopting singlet connectivity with radical assignment.")
                mol = sanitized_mol
            
            else:
                logger.debug("    -> Checking compatibility with singlet-based connectivity.")

                # Create a copy of the temporary read-write `Mol` object and sanitize it.
                sanitized_mol = tmp_rwmol.GetMol()

                rdmolops.SanitizeMol(
                    sanitized_mol,
                    sanitizeOps=rdmolops.SanitizeFlags.SANITIZE_PROPERTIES | rdmolops.SanitizeFlags.SANITIZE_FINDRADICALS,
                    catchErrors=catch_errors
                )

                # Check if the originally set radicals have been removed and which are affected
                affected_radicals = [False for _ in radicals]
                for i, nrad in enumerate(radicals):
                    sanitized_atom = sanitized_mol.GetAtomWithIdx(i)
                    sanitized_nrad = sanitized_atom.GetNumRadicalElectrons()
                    if sanitized_nrad < nrad:
                        affected_radicals[i] = True
                
                # If the radicals have been maintained, simply copy the molecule
                if all([b is False for b in affected_radicals]):
                    logger.debug("- Success: Singlet-based connectivity is VALID.")
                    mol = sanitized_mol
                
                # If radicals would be cleared by sanitization, try to adjust the bond order of the radical site
                else:
                    logger.debug("- Failed: Singlet-based connectivity is INVALID.")
                    
                    affected_sites = [i for i, b in enumerate(affected_radicals) if b is True]
                    logger.debug(f"    -> Affected sites: {affected_sites}")

                    logger.debug("- Trying: Adjusting connectivity around affected radical sites.")

                    # If one of the radicals is set on an aromatic system kekulize the singlet geometry
                    if radical_on_aromatic is True:
                        logger.debug("        * Radical found on aromatic system: KEKULIZING")

                        # Kekulize the singlet geometry
                        rdmolops.SanitizeMol(
                            newmol,
                            sanitizeOps=rdmolops.SanitizeFlags.SANITIZE_KEKULIZE,
                            #catchErrors=catch_errors
                        )

                        # Copy the new kekulized connectivity to the temporary read-write `Mol` object  
                        tmp_rwmol = rdchem.RWMol(mol)
                        for bond in newmol.GetBonds():
                            tmp_rwmol.AddBond(bond.GetBeginAtomIdx(), bond.GetEndAtomIdx(), bond.GetBondType())

                    # Adjust the connectivity of the radical site by breaking multiple bonds and setting charges
                    for i, b in enumerate(affected_radicals):

                        if b is False:
                            continue
                        
                        atom: rdchem.Atom = tmp_rwmol.GetAtomWithIdx(i)
                        current_charge = sum(a.GetFormalCharge() for a in tmp_rwmol.GetAtoms())
                        
                        for bond in atom.GetBonds():
                            bt = bond.GetBondType()

                            idx = bond.GetBeginAtomIdx() if bond.GetBeginAtomIdx() != i else bond.GetEndAtomIdx()
                            other = tmp_rwmol.GetAtomWithIdx(idx)
                            other_charge = other.GetFormalCharge()
                            other_charge += 1 if current_charge < system.charge else -1

                            if bt == rdchem.BondType.TRIPLE:
                                bond.SetBondType(rdchem.BondType.DOUBLE)
                                other.SetFormalCharge(other_charge)
                                logger.debug(f"        * Radical site {i}: changing bond with atom {idx} from TRIPLE to DOUBLE.")
                                break
                            
                            elif bt == rdchem.BondType.DOUBLE:
                                bond.SetBondType(rdchem.BondType.SINGLE)
                                other.SetFormalCharge(other_charge)
                                logger.debug(f"        * Radical site {i}: changing bond with atom {idx} from DOUBLE to SINGLE.")
                                break
                            
                            elif bt == rdchem.BondType.AROMATIC:
                                msg = f"Bond type AROMATIC detected on site ({i}) after kekulization."
                                logger.error(msg)
                                raise RuntimeError(msg)
                    
                    # Convert to `Mol` object
                    mol = tmp_rwmol.GetMol()

                # Sanitize the molecule setting charges and radicals
                rdmolops.SanitizeMol(
                    mol,
                    sanitizeOps=rdmolops.SanitizeFlags.SANITIZE_PROPERTIES | rdmolops.SanitizeFlags.SANITIZE_FINDRADICALS,
                    catchErrors=catch_errors
                )

    # Check the number of unpaired electrons and warn the user if something looks strange
    radical_electrons = [atom.GetNumRadicalElectrons() for atom in mol.GetAtoms()]
    num_radicals = sum(radical_electrons)
    if system.spin == 1:

        if num_radicals % 2 != 0:
            logger.warning("An odd number of radical electrons has been assigned in singlet system.")
        
        else:
            for i, s in enumerate(radical_electrons):
                if s == 2:
                    logger.info(f"{s} unpaired electrons assigned to site {i} in singlet system: converting carbene to singlet")                       
                    carbene_atom = mol.GetAtomWithIdx(i)
                    carbene_atom.SetNumRadicalElectrons(0)

                elif s > 0:
                    logger.info(f"Non-zero ({s}) unpaired electron assigned to site {i} in a singlet system")
    
    else:
        if all([s == 0 for s in radical_electrons]):
            msg = "None of the atoms in the generated `Mol` object have radical electrons even if the system is open-shell."
            logger.error(msg)
            raise RuntimeError(msg)
        
        elif num_radicals != system.spin-1:
            msg = f"The sum of unpaired electrons ({num_radicals}) is different from the one ({system.spin-1}) expected from spin multiplicity."
            logger.error(msg)
            raise RuntimeError(msg)
    
    # Check the sum of formal charges warn the user if something looks strange
    if sum([atom.GetFormalCharge() for atom in mol.GetAtoms()]) != system.charge:
        msg = "The sum of formal charges does not match the total charge of the system."
        logger.error(msg)
        raise RuntimeError(msg)

    return mol


def print_mol(mol: rdchem.Mol, connectivity: bool = True) -> None:
    """
    Given an `rdkit.Chem.rdchem.Mol` object, print a breaf summary of atom properties and connectivity.

    Arguments
    ---------
    mol : rdkit.Chem.rdchem.Mol
        The input `Mol` object
    connectivity: bool
        If set to `True` (default) will print a summary of the connectivity of each atom.
    
    Raises
    ------
    TypeError
        Exception raised if the `mol` argument is not of type `rdkit.Chem.rdchem.Mol`.
    """
    if isinstance(mol, (rdchem.Mol, rdchem.RWMol)) is False:
        raise TypeError(f"The `mol` argument must be of type `rdkit.Chem.rdchem.Mol`. Invalid type {type(mol)} was used.")
    
    atom: rdchem.Atom = None
    print("ATOMS:")
    for atom in mol.GetAtoms():
        idx = atom.GetIdx()
        sym = atom.GetSymbol()
        charge = atom.GetFormalCharge()
        spin = atom.GetNumRadicalElectrons()
        impH = atom.GetTotalNumHs(includeNeighbors=True)
        print(f"Atom {idx:2d}: {sym:2s}, formal charge = {charge}, spin={spin}, Hcount = {impH}")
    
    if connectivity is True:
        print()
        print("CONNECTIVITY:")
        for atom in mol.GetAtoms():
            i = atom.GetIdx()
            neigh_info = []

            for nbr in atom.GetNeighbors():
                j = nbr.GetIdx()
                bond = mol.GetBondBetweenAtoms(i, j)

                # bond type as string
                btype = str(bond.GetBondType())

                neigh_info.append(f"{j} {btype}")

            neigh_str = ", ".join(neigh_info) if neigh_info else "—"
            print(f"{i:2d} to: {neigh_str}")

    print("\n")