name: CI
on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ghcr.io/${{ github.repository_owner }}/spycci-ci:${{ github.sha }}
          secrets: |
            "gh_token=${{ secrets.ORCA_PAT }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run pytest inside container
        run: docker run --rm ghcr.io/${{ github.repository_owner }}/spycci-ci:${{ github.sha }}